version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    links:
      - pg
    volumes:
      - .:/home/app
  pg:
    image: postgres
    ports:
      - "5433:${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      # mongo-data:/data/db
      # mysql -> /var/lib/mysql
      - postgres-data: /var/lib/postgresql/data

volumes:
  postgres-data:
